# Generated by Django 2.2 on 2019-10-21 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_message_to'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='to',
            field=models.IntegerField(default=2),
        ),
    ]
