# Generated by Django 2.2 on 2019-10-21 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_auto_20191021_1546'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='to',
            field=models.IntegerField(default=1),
        ),
    ]
