# Generated by Django 2.2.6 on 2019-10-15 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='account_balance',
            field=models.FloatField(default=1000.0),
        ),
    ]
