# Generated by Django 2.2.6 on 2019-10-17 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='privacy',
            field=models.BooleanField(default=False),
        ),
    ]
