# Generated by Django 2.2.6 on 2019-10-18 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_auto_20191018_1324'),
    ]

    operations = [
        migrations.CreateModel(
            name='friend_req',
            fields=[
                ('req_id', models.IntegerField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='map_to_username',
            fields=[
                ('user_id', models.IntegerField(primary_key=True, serialize=False)),
                ('uname', models.CharField(default='', max_length=300)),
            ],
        ),
    ]
