# Generated by Django 2.2.6 on 2019-10-24 17:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0004_group_user_relation'),
        ('users', '0014_premium_users_current_number_of_groups'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='group',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='poster', to='groups.Group'),
        ),
    ]
