# Generated by Django 2.2.6 on 2019-10-24 16:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='group',
            old_name='owner_id',
            new_name='owner',
        ),
    ]
