# Generated by Django 2.2.6 on 2019-10-28 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0005_group_requests'),
    ]

    operations = [
        migrations.AddField(
            model_name='group_user_relation',
            name='add_reject_perm',
            field=models.BooleanField(default=False),
        ),
    ]
